version: 2
updates:

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 15
    labels:
      - dependencies
    target-branch: master
    versioning-strategy: increase
    ignore:
      - dependency-name: "@aws-sdk/client-s3"
        update-types: ["version-update:semver-patch"]