version: 2
updates:

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 15
    labels:
      - dependencies
    target-branch: master
    versioning-strategy: increase
    ignore:
      - dependency-name: "@aws-sdk/client-s3"
        update-types: ["version-update:semver-patch"]
    groups:
      aws-sdk:
        dependency-type: "production"
        patterns:
          - "@aws-sdk/*"
      remark:
        dependency-type: "development"
        patterns:
          - "remark*"
      types:
        dependency-type: "development"
        patterns:
          - "@types/*"