version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    automerged_updates:
      - match:
          dependency_name: "@types/node"
      - match:
          dependency_name: "ts-node"
      - match:
          dependency_name: "mocha"
      - match:
          dependency_name: "chai"
      - match:
          dependency_name: "typescript"
      - match:
          dependency_name: "aws-sdk"
      - match:
          dependency_name: "music-metadata"
      - match:
          dependency_name: "eslint"
      - match:
          dependency_name: "@typescript-eslint/eslint-plugin"
      - match:
          dependency_name: "@typescript-eslint/parser"
      - match:
          dependency_name: "coveralls"
      - match:
          dependency_name: "nyc"
      - match:
          dependency_name: "@tokenizer/range"
      - match:
          dependency_name: "strtok3"
      - match:
          dependency_name: "karma-jasmine"
      - match:
          dependency_name: "music-metadata"
      - match:
          dependency_name: "karma-firefox-launcher"
