name: Node.js CI
on:
  push:

jobs:

  build:

    runs-on: ubuntu-latest
    environment: AWS

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:

      # Fail fast
      - name: Test AWS OIDC autentication
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::970661486861:role/github-actions-role
          role-session-name: GithubActionS3

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install production dependencies, check node engine compatiblity
        run: yarn install --production=true

      - name: Install development dependencies
        run: yarn install --production=false --ignore-engines

      - name: Build & Code analysis
        run: yarn run lint

      - name: Build
        run: yarn run build

      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            lib/**/*.js
            lib/**/*.js.map
            lib/**/*.d.ts
            test/**/*.js
            test/**/*.js.map

  test:

    runs-on: ubuntu-latest
    environment: AWS
    needs: build

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x, 18.x]

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:

      - name: Configure AWS OIDC Session
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::970661486861:role/github-actions-role
          role-session-name: GithubActionS3

      - name: 'Checkout the repository'
        uses: actions/checkout@v2

      - name: Test with Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --ignore-engines

      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: build

      - name: Test with Node.js ${{ matrix.node-version }}
        run: yarn run test
